//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Properties.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.A.E..
        /// </summary>
        internal static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        internal static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        internal static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        internal static string CA_AB {
            get {
                return ResourceManager.GetString("CA_AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        internal static string CA_BC {
            get {
                return ResourceManager.GetString("CA_BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        internal static string CA_MB {
            get {
                return ResourceManager.GetString("CA_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brunswick.
        /// </summary>
        internal static string CA_NB {
            get {
                return ResourceManager.GetString("CA_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland and Labrador.
        /// </summary>
        internal static string CA_NL {
            get {
                return ResourceManager.GetString("CA_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia.
        /// </summary>
        internal static string CA_NS {
            get {
                return ResourceManager.GetString("CA_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territories.
        /// </summary>
        internal static string CA_NT {
            get {
                return ResourceManager.GetString("CA_NT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunavut.
        /// </summary>
        internal static string CA_NU {
            get {
                return ResourceManager.GetString("CA_NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        internal static string CA_ON {
            get {
                return ResourceManager.GetString("CA_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prince Edward Island.
        /// </summary>
        internal static string CA_PE {
            get {
                return ResourceManager.GetString("CA_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        internal static string CA_QC {
            get {
                return ResourceManager.GetString("CA_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        internal static string CA_SK {
            get {
                return ResourceManager.GetString("CA_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yukon.
        /// </summary>
        internal static string CA_YT {
            get {
                return ResourceManager.GetString("CA_YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People&apos;s Republic of China.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia and Montenegro (Former).
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        internal static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        internal static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong S.A.R..
        /// </summary>
        internal static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        internal static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        internal static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        internal static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        internal static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        internal static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        internal static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        internal static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        internal static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        internal static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao P.D.R..
        /// </summary>
        internal static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        internal static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principality of Monaco.
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia (FYROM).
        /// </summary>
        internal static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao S.A.R..
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        internal static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        internal static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        internal static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        internal static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republic of the Philippines.
        /// </summary>
        internal static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamic Republic of Pakistan.
        /// </summary>
        internal static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        internal static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad and Tobago.
        /// </summary>
        internal static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan.
        /// </summary>
        internal static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        internal static string US_AK {
            get {
                return ResourceManager.GetString("US_AK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama.
        /// </summary>
        internal static string US_AL {
            get {
                return ResourceManager.GetString("US_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkansas.
        /// </summary>
        internal static string US_AR {
            get {
                return ResourceManager.GetString("US_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa.
        /// </summary>
        internal static string US_AS {
            get {
                return ResourceManager.GetString("US_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arizona.
        /// </summary>
        internal static string US_AZ {
            get {
                return ResourceManager.GetString("US_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California.
        /// </summary>
        internal static string US_CA {
            get {
                return ResourceManager.GetString("US_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorado.
        /// </summary>
        internal static string US_CO {
            get {
                return ResourceManager.GetString("US_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecticut.
        /// </summary>
        internal static string US_CT {
            get {
                return ResourceManager.GetString("US_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District of Columbia.
        /// </summary>
        internal static string US_DC {
            get {
                return ResourceManager.GetString("US_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delaware.
        /// </summary>
        internal static string US_DE {
            get {
                return ResourceManager.GetString("US_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florida.
        /// </summary>
        internal static string US_FL {
            get {
                return ResourceManager.GetString("US_FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string US_GA {
            get {
                return ResourceManager.GetString("US_GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        internal static string US_GU {
            get {
                return ResourceManager.GetString("US_GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaii.
        /// </summary>
        internal static string US_HI {
            get {
                return ResourceManager.GetString("US_HI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iowa.
        /// </summary>
        internal static string US_IA {
            get {
                return ResourceManager.GetString("US_IA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idaho.
        /// </summary>
        internal static string US_ID {
            get {
                return ResourceManager.GetString("US_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illinois.
        /// </summary>
        internal static string US_IL {
            get {
                return ResourceManager.GetString("US_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiana.
        /// </summary>
        internal static string US_IN {
            get {
                return ResourceManager.GetString("US_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kansas.
        /// </summary>
        internal static string US_KS {
            get {
                return ResourceManager.GetString("US_KS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentucky.
        /// </summary>
        internal static string US_KY {
            get {
                return ResourceManager.GetString("US_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Louisiana.
        /// </summary>
        internal static string US_LA {
            get {
                return ResourceManager.GetString("US_LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massachusetts.
        /// </summary>
        internal static string US_MA {
            get {
                return ResourceManager.GetString("US_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maryland.
        /// </summary>
        internal static string US_MD {
            get {
                return ResourceManager.GetString("US_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maine.
        /// </summary>
        internal static string US_ME {
            get {
                return ResourceManager.GetString("US_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michigan.
        /// </summary>
        internal static string US_MI {
            get {
                return ResourceManager.GetString("US_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minnesota.
        /// </summary>
        internal static string US_MN {
            get {
                return ResourceManager.GetString("US_MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missouri.
        /// </summary>
        internal static string US_MO {
            get {
                return ResourceManager.GetString("US_MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mississippi.
        /// </summary>
        internal static string US_MS {
            get {
                return ResourceManager.GetString("US_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montana.
        /// </summary>
        internal static string US_MT {
            get {
                return ResourceManager.GetString("US_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Carolina.
        /// </summary>
        internal static string US_NC {
            get {
                return ResourceManager.GetString("US_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Dakota.
        /// </summary>
        internal static string US_ND {
            get {
                return ResourceManager.GetString("US_ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebraska.
        /// </summary>
        internal static string US_NE {
            get {
                return ResourceManager.GetString("US_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hampshire.
        /// </summary>
        internal static string US_NH {
            get {
                return ResourceManager.GetString("US_NH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Jersey.
        /// </summary>
        internal static string US_NJ {
            get {
                return ResourceManager.GetString("US_NJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mexico.
        /// </summary>
        internal static string US_NM {
            get {
                return ResourceManager.GetString("US_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevada.
        /// </summary>
        internal static string US_NV {
            get {
                return ResourceManager.GetString("US_NV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York.
        /// </summary>
        internal static string US_NY {
            get {
                return ResourceManager.GetString("US_NY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohio.
        /// </summary>
        internal static string US_OH {
            get {
                return ResourceManager.GetString("US_OH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oklahoma.
        /// </summary>
        internal static string US_OK {
            get {
                return ResourceManager.GetString("US_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oregon.
        /// </summary>
        internal static string US_OR {
            get {
                return ResourceManager.GetString("US_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pennsylvania.
        /// </summary>
        internal static string US_PA {
            get {
                return ResourceManager.GetString("US_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string US_PR {
            get {
                return ResourceManager.GetString("US_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhode Island.
        /// </summary>
        internal static string US_RI {
            get {
                return ResourceManager.GetString("US_RI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Carolina.
        /// </summary>
        internal static string US_SC {
            get {
                return ResourceManager.GetString("US_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Dakota.
        /// </summary>
        internal static string US_SD {
            get {
                return ResourceManager.GetString("US_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennessee.
        /// </summary>
        internal static string US_TN {
            get {
                return ResourceManager.GetString("US_TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas.
        /// </summary>
        internal static string US_TX {
            get {
                return ResourceManager.GetString("US_TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utah.
        /// </summary>
        internal static string US_UT {
            get {
                return ResourceManager.GetString("US_UT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virginia.
        /// </summary>
        internal static string US_VA {
            get {
                return ResourceManager.GetString("US_VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands.
        /// </summary>
        internal static string US_VI {
            get {
                return ResourceManager.GetString("US_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermont.
        /// </summary>
        internal static string US_VT {
            get {
                return ResourceManager.GetString("US_VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washington.
        /// </summary>
        internal static string US_WA {
            get {
                return ResourceManager.GetString("US_WA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisconsin.
        /// </summary>
        internal static string US_WI {
            get {
                return ResourceManager.GetString("US_WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Virginia.
        /// </summary>
        internal static string US_WV {
            get {
                return ResourceManager.GetString("US_WV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyoming.
        /// </summary>
        internal static string US_WY {
            get {
                return ResourceManager.GetString("US_WY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        internal static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivarian Republic of Venezuela.
        /// </summary>
        internal static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen.
        /// </summary>
        internal static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        internal static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
